### ISSUE TITLE
application crashes running orion.sch example

### ISSUE THREAD

**Issue by astroscot** [dcf21/star-charter#4]
After installing star-charter running under Ubuntu in VirtualBox the first example run was the orion.sch example provided. The code quickly crashed with the following errors after running the command 

../bin/starchart.bin orion.sch

Error : Fatal Error encountered in src/astroGraphics/constellations.c at line 146:
Error: Could not open constellation stick figures

![Error-Orion sch-example](https://user-images.githubusercontent.com/42391620/99147336-0c58a880-2678-11eb-8569-9b57314ef22b.jpg)

**Comment by astroscot** [comment]
This issue is resolved.

**Comment by jackschmidt** [comment]
This still happened to me. The problem is that `ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/hip_main.dat.gz` no longer exists so `setup.sh` creates a 0 length file.

To fix, you can download `ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/hip_main.dat` to `data/constellations/downloads` and then run `gzip -9f hip_main.dat` to compress it to the expected filename. Then in the main directory, run `setup.sh` again.
